apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-app
  template:
    metadata:
      labels:
        app: mnist-app
    spec:
      containers:
        - name: mnist-container
          image: mnist-fast-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
